services:
  app:
    image: thiagost32/desafioitauapi:1.0
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          memory: "256M"
          cpus: "0.25"
        limits:
          memory: "512M"
          cpus: "0.50"
    ports:
      - "8080:8080"
